# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    #Python-3.6:
    build:
        docker:
            - image: circleci/python:3.6.4-stretch-browsers

        working_directory: ~/repo

        steps:
            - checkout

            - run:
                name: install apt packages
                command: |
                    sudo apt-get update
                    sudo apt-get install -y libgtk2.0-dev libgtk-3-dev libjpeg-dev libtiff-dev \
                            libsdl1.2-dev libgstreamer-plugins-base1.0-dev libnotify-dev freeglut3 \
                            freeglut3-dev libsm-dev libwebkitgtk-dev libwebkitgtk-3.0-dev libxtst-dev

            - run:
                name: install python packages
                command: |
                    python -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt

            - run: 
                name: build wxWidgets
                command: |
                    python3 build.py --jobs=4 dox build_wx 

            - run: 
                name: build wxPython
                command: |
                    python build.py --jobs=4 etg --nodoc sip build_py
                    python build.py bdist_wheel
                    python build.py install

          